//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Servicio { get; set; }
        public string Local { get; set; }
        public string Hora { get; set; }
        public int CodReserva { get; set; }
        public string CodCliente { get; set; }
        public string Mascota { get; set; }
        public Nullable<int> CodMascota { get; set; }
        public Nullable<int> precio { get; set; }
        public string DiaSemana { get; set; }
    }
}
